references:
  defaults: &defaults
    working_directory: ~/interactor
    docker:
      - image: circleci/node:10-browsers

  cache_key: &cache_key
    interactor-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/

version: 2.0
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          key: *cache_key
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          name: Save cache
          key: *cache_key
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - interactor
            - .ssh

  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Lint package
          command: yarn lint

  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Run tests
          command: yarn test --browser chrome

workflows:
  version: 2
  default:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install